### PR TITLE
Set package name checking to false

### PR DESCRIPTION
**Pull request by andycate**
Changed the package name checking to false. Otherwise, detekt complains even if the package name is correct.

### CODE REVIEW

**Comment by emmaworley** [comment]
I thought I was able to fix this earlier by changing the package name. What name is it complaining about?

**Comment by andycate** [comment]
I ran `cookiecutter https://github.com/team5499/frc-template`, and then for package name, I put `frc2018Classroom` and when it got to the detekt hook, it complained about the package name.

**Comment by andycate** [comment]
In `frc2018Kotlin`, the package naming check is disabled as well
but in the template, it is enabled

**Comment by andycate** [comment]
so really, it is just a backport

**Comment by emmaworley** [comment]
That's because frc2018Classroom is actually an invalid package name. It's checking against a regex here: https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/PackageNaming.kt. I'd personally rather leave all the detekt options as default (except for maxIssues) in the template, and let people customize them for their projects if they need to.

**Comment by andycate** [comment]
Oh, so the package name should be all lowercase?

**Pull request closed without merging**
